version: "3.7"

services:
  mongodb:
    image: mongo
    networks:
      - dev-network
  api-node:
    build:
      dockerfile: node.dockerfile
      context: ./api-nasa/
    volumes:
      - ./api-nasa:/node-app
      - /node-app/node_modules
    ports:
      - "3333:3000"
    image: node-exoplanet
    container_name: container-node01
    networks:
      - dev-network
    depends_on:
      - "mongodb"
  app:
    build:
      dockerfile: exoplanet-nasa.dockerfile
      context: ./app/
    volumes:
      - ./app:/react-app
      - /react-app/node_modules
    ports:
      - "3000:3000"
    image: react-exoplanet
    container_name: container-react
    networks:
      - dev-network
    depends_on:
      - "api-node"
networks:
  dev-network:
    driver: "bridge"
